FORMAT: 1A
HOST: http://telefonicaid.github.io/fiware-orion/api/v2/
TITLE: FIWARE-NGSI v2 Specification
DATE: 30 July 2015
VERSION: abcedefg
PREVIOUS_VERSION: jhdfgh
APIARY_PROJECT: test5950
SPEC_URL: http://example.com/apib
GITHUB_SOURCE: http://github.com/telefonicaid/fiware-orion.git



# FIWARE-NGSI v2 Specification

This specification defines the FIWARE-NGSI version 2 API. FIWARE-NGSI v2 is intended to manage all the whole lifecycle of
context information including updates, queries, registrations and subscriptions.

## Editors

  + José Manuel Cantera Fonseca, Telefónica I+D
  + Fermín Galán, Telefónica I+D. 
  + Tobias Jacobs, NEC
  
## Acknowledgements

The editors would like to express their gratitude to the following people who actively contributed to this specification:
Juan José Hierro, Marcos Reyes, Ken Gunnar, Antonio López, ... 

  

## Status

This is a work in progress and is changing on a daily basis.


## Copyright

Copyright - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia, nisl non tristique sollicitudin, nisl lectus finibus erat, a mattis orci turpis non nunc. Maecenas convallis diam odio, vel blandit turpis varius at. Duis hendrerit lectus non viverra vehicula. Nunc eu eros nec nisl facilisis commodo. Nam at dui arcu. Quisque vitae augue metus. Sed quis consequat lacus. Duis sed eros rhoncus, fringilla mauris ut, interdum orci. Cras sodales facilisis luctus. Quisque fringilla tincidunt sapien at iaculis. Phasellus tempus a enim ac volutpat. Ut tincidunt fermentum massa quis sagittis. Ut non scelerisque risus, a dignissim odio.

## License

License section

# Specification

## Introduction

The FIWARE NGSI (Next Generation Service Interface) API defines: 

* a **data model** for context information, based on a simple information model using the notion of *context entities*
* a **context data interface** for exchanging information by means of query, subscription, and update operations
* a **context availability interface** for exchanging information on how to obtain context information
(whether to separate the two interfaces is currently under discussion).
* a set of typical **roles** played by NGSI-compliant components


## Data Structures

### Choice (object)
    + choice (string) - Text
    + url aa (string) - Choice URL
    + votes (number) - Number of votes
    + primer_nivel (object) - Test recursividad
        + segundo_nivel: stringValor (string)
        + otro_segundo (string)
        + tercer_nivel (object)
            + terString: valor33 (string) - Choice level 3

### Question (object)
      + question (string) - Text of the question
      + published_at (string) - An ISO8601 date when the question was published.
      + url (string, required) - URL 
      + choices (array[Choice]) - An array of Choice objects.


# REST API

# Group Root

## Action with attributes and without parent [GET /v2]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

+ Attributes(object)
    + entities_url: entityExample(required, string) - URL which points to the entities resource
    + types_url (required, string) - URL which points to the types resource
    + subscriptions_url (required, string) - URL which points to the subscriptions resource
    + registrations_url (required, string) - URL which points to the registrations resource


+ Request get_with_body (application/json)

    + Body

            {
                "ambientNoise": 31.5
            }

+ Request get_without_body (application/json)

+ Response 200 (application/json)

        {
            "entities_url":      "/v2/entities",
            "types_url":         "/v2/types",
            "subscriptions_url": "/v2/subscriptions",
            "registrations_url": "/v2/registrations"
        }


# Group Entities

Resources related to Context Entities.

## Resource with attributes [/v2/entities{?limit,offset,options,type,id,idPattern,q,geometry,coords,attrs}]

bla bla bla

+ Attributes(object)
    + entities_url: entityExample (required, string) - URL which points to the entities resource
    + types_url (required, string) - URL which points to the types resource
    + subscriptions_url (required, string) - URL which points to the subscriptions resource
    + registrations_url (required, object) - URL which points to the registrations resource
        + segundo_nivel (object) - Segundo nivel
            + tercerNivel (object) - tercer nivel
                + cuartoNivel: pepe (string) - Es pepe

### Action without attr but with resoruce attr [GET /v2/entities{?limit,offset,options,type,id,idPattern,q,geometry,coords,attrs}]

Retrieves a list of entities which match criteria defined by the following parameters: `id`, `type`, `idPattern`, `q`,
`geometry` and `coords`


+ Request get_with_body (application/json)

    + Body

            {
                "ambientNoise": 31.5
            }

+ Request get_without_body (application/json)

+ Response 200 (application/json)

        {
            "entities_url":      "/v2/entities",
            "types_url":         "/v2/types",
            "subscriptions_url": "/v2/subscriptions",
            "registrations_url": "/v2/registrations"
        }

### action with attr link [POST /v2/entities]

+ Attributes (Choice)


+ Request get_with_body (application/json)

    + Body

            {
                "ambientNoise": 31.5
            }

+ Request get_without_body (application/json)

+ Response 200 (application/json)

        {
            "entities_url":      "/v2/entities",
            "types_url":         "/v2/types",
            "subscriptions_url": "/v2/subscriptions",
            "registrations_url": "/v2/registrations"
        }

## Resource with link [/v2/entities2{?limit,offset,options,type,id,idPattern,q,geometry,coords,attrs}]


bla bla bla

+ Attributes(Choice)

### Action without attr but with resoruce link [GET /v2/entities{?limit,offset,options,type,id,idPattern,q,geometry,coords,attrs}]

Retrieves a list of entities which match criteria defined by the following parameters: `id`, `type`, `idPattern`, `q`,
`geometry` and `coords`


+ Request get_with_body (application/json)

    + Body

            {
                "ambientNoise": 31.5
            }

+ Request get_without_body (application/json)

+ Response 200 (application/json)

        {
            "entities_url":      "/v2/entities",
            "types_url":         "/v2/types",
            "subscriptions_url": "/v2/subscriptions",
            "registrations_url": "/v2/registrations"
        }

+ Response 404 (application/json)

### action with attr link [POST /v2/entities]

+ Attributes (Choice)


+ Request get_with_body (application/json)

    + Body

            {
                "ambientNoise": 31.5
            }

+ Request get_without_body (application/json)

+ Response 200 (application/json)

        {
            "entities_url":      "/v2/entities",
            "types_url":         "/v2/types",
            "subscriptions_url": "/v2/subscriptions",
            "registrations_url": "/v2/registrations"
        }


### attributes in request test [POST /v2/entitiess]

+ Attributes (Choice)


+ Request get_with_body (application/json)

    + Body

            {
                "ambientNoise": 31.5
            }

+ Request get_without_body_but_attr (application/json)

    + Attributes (object)
        + entities_url: entityExampleREQ (required, string) - URL which points to the entities resource


+ Request get_without_body_but_attr_linked (application/json)

    + Attributes (Choice)

+ Response 200 (application/json)

    + Attributes (object)
        + entities_url: entityExampleRES (required, string) - URL which points to the entities resource


## atributos con recursividad [GET /v2/entitiesR]

+ Attributes (object)
    + primer_nivel (object)
        + city: ciudad (string) - Descripcion de ciudad
        + Country: pais (string) - descripcion de pais
        + segundo_nivel (object) - segundo nivel
            + con_valor: defaultValue (string) - 2.1
            + sin_valor (string) - string sin valor
            + tercer_nivel (object) - tercer nivel
                + con_valor: valor3 - (string) string con valor
                + sin_valor (string) - string sin valor


+ Request get_recursive (application/json)

+ Request atributo_referenciado_recurso (application/json)

    + Attributes (Resource with attributes)

+ Response 200 (application/json)